### PR TITLE
Health Bars

### PR DESCRIPTION
**Pull request by SoySerhio507**
Created a helper for the health bar and the stats menu to remove code smells. Added the health bar for the player. The health is fixed right now, will be connecting to the player entity in the next push.

### CODE REVIEW

**Review by qwet1235 — APPROVED** [review]
Looks nice. We should implement the scaling later once we merge more branches

**Review by Raiyankr — APPROVED** [review]
The code looks a lot cleaner than before!
- Great job on the documentations, they were easy to follow along
- You used a similar structure of implementing your use case as me, which was super convenient for me to check!

**Review by keikei-jaffar — APPROVED** [review]
Great work and documentation! The showStarts feature is pretty user-friendly and easy-to-understand. I like your code's flexibility, and openness to future changes and improvements!

**Review by kevinzshen — COMMENTED** [review]
Great job following clean architecture and SOLID principles. Seems like you got rid of many code smells. Smells delicious! 👨🏼‍🍳

**Review by khushil-sketch — APPROVED** [review]
Great work on the regenerative Health feature, this will help with the Shop potions that Kevin has to implement. He can call this method when the player buys a health potion

**Pull request merged**
