### PR TITLE
Cleaned up the Gui 

### PR DESCRIPTION
**Pull request by Raiyankr**
- Added Use Case Layers
- Interface Adapter Layers
- Removed some dependencies 
- Commented TODOS: for things we all need to do

😌 👀

### CODE REVIEW

**Review by SoySerhio507 — DISMISSED** [review]
Please remember to document your code next time. These changes are very important to be able to proceed with clean architecture on other branches 👍

**Review by qwet1235 — CHANGES_REQUESTED** [review]
I accidentally requested a new review. This can be ignore hehe

**Review by SoySerhio507 — APPROVED** [review]
Please remember to document your code next time. These changes are very important to be able to proceed with clean architecture on other branches 👍

**Review by qwet1235 — APPROVED** [review]
good

**Review by keikei-jaffar — APPROVED** [review]
This is amazing! With the clean version, there's clear communication with someone who works with what you've written. Being able to return to previously written code and understand what it does is key, especially in your LoadLevelImage class.

**Review by khushil-sketch — COMMENTED** [review]
Good work on implementing CLEAN  Architecture on your code. I can now follow your code more closely and understand what's happening.

**Comment by Raiyankr** [comment]
Alright boys and girls, this can be the foundation for the rest of the clean architecture.  This has the basic clean architecture, controller and use case workflow.  Good luck soldiers  😎 🫡

˚∆˚

**Pull request merged**
