### PR TITLE
Collision

### PR DESCRIPTION
**Pull request by tanverzahed**
Completed collision for enemy to wall, enemy to player, player to enemy (its different), and player to enemy. There are bugs that needs to fixed though.

### CODE REVIEW

**Review by qwet1235 — APPROVED** [review]
My part also relies heavily on the entity's hitbox. We will have to find a way to merge our implementations so that the hitbox works for both collisions and attacks

**Comment by Raiyankr** [comment]
The Code is easy to follow along and organized well. I was thinking if it would be possible to remove the wall location from Player and have it in a separate class. Making a separate class that 

- creates the collisions, 
- places the boxes accordingly and 
- keeps track of when collisions happen.

**Review by qwet1235 — COMMENTED** [review]
Also, one more note is that I think the Player's hitbox might have to be an ellipse/circle rather than a rectangle because of our Player sprite design

**Comment by Raiyankr** [comment]
The Code is easy to follow along and organized well. I was thinking if it would be possible to remove the wall location from Player and have it in a separate class. Making a separate class that

creates the collisions,
places the boxes accordingly and
keeps track of when collisions happen.

**Review by Raiyankr — CHANGES_REQUESTED** [review]
The Code is easy to follow along and organized well. I was thinking if it would be possible to remove the wall location from Player and have it in a separate class. Making a separate class that

creates the collisions,
places the boxes accordingly and
keeps track of when collisions happen.

**Review by Raiyankr — APPROVED** [review]

**Review by SoySerhio507 — APPROVED** [review]
Thank you for fixing the bugs. Please remember to document these classes and methods in the future.

**Review by khushil-sketch — COMMENTED** [review]
i LIKE THE collision stuff - I can add this stuff to my entity code - interfaces etc.

**Review by khushil-sketch — APPROVED** [review]
Excellent

**Pull request merged**
