### PR TITLE
Health Bar

### PR DESCRIPTION
**Pull request by SoySerhio507**
…player health to better reflected its applied usage. Documented instance variables and methods related to player health. Missing documentation on Graphics g parameter for drawHealthBar().

### CODE REVIEW

**Review by qwet1235 — APPROVED** [review]
I think your implementation for health looks much better. Your code looks more organized and does a nice job of updating both the current health and the max health (if the player gets a potion).

**Review by SoySerhio507 — COMMENTED** [review]
Merged all the code related to the health bar. Refactored method and variable names to be consistent with what is being displayed

**Review by SoySerhio507 — COMMENTED** [review]
Finished merging last details on the local branch with the remote branch to merge

**Comment by SoySerhio507** [comment]
Merging to the attack methods branch

**Pull request merged**
