### PR TITLE
Enemy Manager

### PR DESCRIPTION
**Pull request by keikei-jaffar**
Added the EnemyManagerInteractor, RangedEnemy and the abstract Enemy classes

### CODE REVIEW

**Review by Raiyankr — APPROVED** [review]
I think the basic foundation for enemy manager class is off to a good start.

- Whoever is working with the enemy manager should double check to confirm if this class is doing everything it needs to do. 

I am leaving this an approve, but whoever is using this class please double check to make sure it is working how you want it to work

**Review by tanverzahed — CHANGES_REQUESTED** [review]
Everything looks good, since I will be using the list containing all the enemies, I really appreciate  how you implemented that. Besides that the enemy manager looks good. Please provide a controller for me that access that information through.

**Review by tanverzahed — APPROVED** [review]
Everything looks good, since I will be using the list containing all the enemies, I really appreciate how you implemented that. Besides that the enemy manager looks good. I like that you added the controllers for me to access those information through.

**Review by qwet1235 — APPROVED** [review]
I think your interactors look good. It has the methods that we need to access all enemies at once. Also, we should update the entities because I think it contains a lot of unecessary code and is not clean

**Review by kevinzshen — APPROVED** [review]
Great job with your documentation, particularly in EnemyManagerInteractor.java. Your comments made it very easy to read and understand your code. Keep up the great work!

**Pull request merged**
