### PR TITLE
Speed Bar

### PR DESCRIPTION
**Pull request by SoySerhio507**

### CODE REVIEW

**Review by keikei-jaffar — APPROVED** [review]
The diagonal movements are way better now. Great move!

**Review by qwet1235 — DISMISSED** [review]
The updates to your use case looks good. I think the visual looks much cooler and it's nice that it updates as the player moves

**Review by kevinzshen — APPROVED** [review]
Good job fixing the speed bar! It works really well

**Review by Raiyankr — APPROVED** [review]
The speed bar looks a lot cleaner now.
- Thanks for documenting your methods!

**Review by keikei-jaffar — APPROVED** [review]
Great work on the speed change!

**Pull request merged**
