### PR TITLE
Basic shop system, Health border and Stats GUI

### PR DESCRIPTION
**Pull request by Raiyankr**
- Added the basic mechanism for item visualization, spawning, and removing.
- Added health bar background GUI as well as stats bar. 
- Health Bar shows max health, and Stats bar scales as player buys potion and progresses throughout game.
- Made the GUI look pretty :)

### CODE REVIEW

**Review by tanverzahed — DISMISSED** [review]
Everything looks good, we do need to decide on how the health increases whether thats % based or solid numbers.
Besides that I really like the theme you have made and for sure need to keep making everything that we add in the future similar theme to that.

**Comment by SoySerhio507** [comment]
Test

**Comment by khushil-sketch** [comment]
Code looks good, I like the new system of having just 1 health bar instead of 2.

**Comment by qwet1235** [comment]
I think the visuals look very good. We should make the health bar rescale based on the max health. Also, if there is enough time, it would be nice to show the player's attack damage value. :)

**Review by qwet1235 — APPROVED** [review]
We should make the health bar rescale based on the max health. Also, if there is enough time, it would be nice to show the player's attack damage value. Overall looks really good tho :)

**Review by khushil-sketch — COMMENTED** [review]
Thank you for uploading the Shop Sytem code, this will help me create the shop entity class. The code looks good with the new GUI designs. There is now only 1 health bar that is updated when the player recovers/ takes a potion as compared to having a HP bar and health bar which both have to be updated and changed in different ways - this is much simpler to comprehend and is more straight forward.

**Review by khushil-sketch — DISMISSED** [review]

**Review by tanverzahed — APPROVED** [review]
Everything looks good, we do need to decide on how the health increases whether thats % based or solid numbers.
Besides that I really like the theme you have made and for sure need to keep making everything that we add in the future similar theme to that.

This is just a reapproval.

**Review by khushil-sketch — APPROVED** [review]
Thank you for uploading the Shop Sytem code, this will help me create the shop entity class. The code looks good with the new GUI designs. There is now only 1 health bar that is updated when the player recovers/ takes a potion as compared to having a HP bar and health bar which both have to be updated and changed in different ways - this is much simpler to comprehend and is more straight forward.

**Review by SoySerhio507 — APPROVED** [review]
Really good progress. After merging with the main branch we will merge the full functionality of the health bar that was built on a separate branch.

**Comment by kevinzshen** [comment]
Code looks pretty good. However, I do think that we could increase the amount of documentation. That way it would be easier for people and team members to understand the code more quickly.

**Pull request merged**
